configCheck: from application-jbeutel.yml

# @david the appId i put here is for our which needs to go through the official
# facebook approval process. i'm using one of my already-approved appIds and
# tokens in the production site in the meantime. also, i didn't want to check
# in our actual page token into source code since HACC17 github is public
facebook:
    messenger:
        appId: 278170452670068
        origin: http://localhost:8080
        pageToken: EAAD8ZCpsEtnQBAGlsQfponq5ZCSBpT6jkkE8ScOdH30dLbDTJlFaycAQBmulN35XfeBAzo5kGViaUJjcINMPUWuu4ZBoMvcFp1YL8sj1BNkhwu9sZACN7DaMra8dmZACoDb8MCS9coohsZBHCvaoqtwKZByyJ7SfEUGxtExzq1W0QZDZD
        pageId: 480155449028959

# The duplicate code in environments seems to be required in Grails 3.3.0:
# https://stackoverflow.com/questions/46138943/does-the-grails-3-3-environments-config-work-inconsistently-in-spring-profiles
environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:postgresql://localhost:5432/alohavolunteer
            driverClassName: org.postgresql.Driver
            username: avdbusr
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:postgresql://localhost:5432/alohavolunteer
            driverClassName: org.postgresql.Driver
            username: avdbusr
    production:
        dataSource:
            dbCreate: create-drop
            url: jdbc:postgresql://localhost:5432/alohavolunteer
            driverClassName: org.postgresql.Driver
            username: avdbusr
