facebook:
    messenger:
        verifyToken: ${FACEBOOK_MESSENGER_VERIFY_TOKEN}
        appId: ${FACEBOOK_APP_ID}
        origin: ${ORIGIN}
        pageToken: ${FACEBOOK_PAGE_TOKEN}
        pageId: ${FACEBOOK_PAGE_ID}

# The duplicate code in environments seems to be required in Grails 3.3.0:
# https://stackoverflow.com/questions/46138943/does-the-grails-3-3-environments-config-work-inconsistently-in-spring-profiles
environments:
    production:
        dataSource:
            dbCreate: update
            url: ${JDBC_DATABASE_URL}
            driverClassName: org.postgresql.Driver
            username: ${JDBC_DATABASE_USERNAME}
            password: ${JDBC_DATABASE_PASSWORD}
